import type { User, Course, Progress, Achievement, Badge } from "./types";

// ─── Instructors ────────────────────────────────────────────────────

export const MOCK_INSTRUCTORS: User[] = [
  {
    id: "inst-1",
    name: "Arjun Mehta",
    email: "arjun@spire.dev",
    avatar_url: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&q=80",
    role: "instructor",
    bio: "Senior full-stack engineer with 10+ years building scalable web applications. Ex-Flipkart, ex-Razorpay.",
    created_at: "2024-06-01T00:00:00Z",
    updated_at: "2025-01-15T00:00:00Z",
  },
  {
    id: "inst-2",
    name: "Priya Sharma",
    email: "priya@spire.dev",
    avatar_url: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200&q=80",
    role: "instructor",
    bio: "Data scientist and ML engineer. Passionate about making complex topics accessible. Published researcher.",
    created_at: "2024-07-10T00:00:00Z",
    updated_at: "2025-02-20T00:00:00Z",
  },
  {
    id: "inst-3",
    name: "Rahul Kapoor",
    email: "rahul@spire.dev",
    avatar_url: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=200&q=80",
    role: "instructor",
    bio: "Mobile and cloud architect. Google Developer Expert. Speaker at JSConf and ReactConf India.",
    created_at: "2024-08-15T00:00:00Z",
    updated_at: "2025-03-01T00:00:00Z",
  },
];

// ─── Courses ────────────────────────────────────────────────────────

export const MOCK_COURSES: Course[] = [
  {
    id: "course-1",
    title: "Full-Stack Web Development",
    slug: "full-stack-web-development",
    description:
      "Master modern web development from front to back. Build production-ready applications with React, Node.js, PostgreSQL, and deploy to the cloud.",
    short_description: "Build production-ready full-stack apps with React & Node.js",
    thumbnail_url: "https://images.unsplash.com/photo-1627398242454-45a1465c2479?w=600&q=80",
    instructor_id: "inst-1",
    instructor: MOCK_INSTRUCTORS[0],
    category: "Web Development",
    level: "Intermediate",
    price: 0,
    is_free: true,
    duration_hours: 42.5,
    lessons_count: 64,
    enrolled_count: 12430,
    rating: 4.8,
    ratings_count: 2156,
    tags: ["react", "node.js", "postgresql", "typescript"],
    is_published: true,
    created_at: "2024-09-01T00:00:00Z",
    updated_at: "2025-03-10T00:00:00Z",
  },
  {
    id: "course-2",
    title: "React Mastery",
    slug: "react-mastery",
    description:
      "Go beyond the basics. Learn advanced React patterns, performance optimization, state management, and testing strategies used by top engineering teams.",
    short_description: "Advanced React patterns, performance & testing",
    thumbnail_url: "https://images.unsplash.com/photo-1633356122544-f134324a6cee?w=600&q=80",
    instructor_id: "inst-1",
    instructor: MOCK_INSTRUCTORS[0],
    category: "Frontend",
    level: "Advanced",
    price: 499,
    is_free: false,
    duration_hours: 28,
    lessons_count: 42,
    enrolled_count: 8750,
    rating: 4.9,
    ratings_count: 1832,
    tags: ["react", "next.js", "testing", "performance"],
    is_published: true,
    created_at: "2024-10-15T00:00:00Z",
    updated_at: "2025-02-28T00:00:00Z",
  },
  {
    id: "course-3",
    title: "Python for Data Science",
    slug: "python-for-data-science",
    description:
      "Learn Python from scratch and apply it to real-world data science problems. Covers pandas, NumPy, matplotlib, and introductory machine learning with scikit-learn.",
    short_description: "Python, pandas, NumPy & intro to machine learning",
    thumbnail_url: "https://images.unsplash.com/photo-1526379095098-d400fd0bf935?w=600&q=80",
    instructor_id: "inst-2",
    instructor: MOCK_INSTRUCTORS[1],
    category: "Data Science",
    level: "Beginner",
    price: 0,
    is_free: true,
    duration_hours: 36,
    lessons_count: 52,
    enrolled_count: 15200,
    rating: 4.7,
    ratings_count: 3410,
    tags: ["python", "pandas", "numpy", "machine-learning"],
    is_published: true,
    created_at: "2024-08-20T00:00:00Z",
    updated_at: "2025-01-20T00:00:00Z",
  },
  {
    id: "course-4",
    title: "Cloud Architecture with AWS",
    slug: "cloud-architecture-with-aws",
    description:
      "Design and deploy scalable cloud architectures on AWS. Covers EC2, S3, Lambda, DynamoDB, and infrastructure as code with Terraform.",
    short_description: "Scalable cloud solutions with AWS & Terraform",
    thumbnail_url: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=600&q=80",
    instructor_id: "inst-3",
    instructor: MOCK_INSTRUCTORS[2],
    category: "Cloud & DevOps",
    level: "Intermediate",
    price: 999,
    is_free: false,
    duration_hours: 32,
    lessons_count: 48,
    enrolled_count: 6320,
    rating: 4.6,
    ratings_count: 980,
    tags: ["aws", "terraform", "serverless", "devops"],
    is_published: true,
    created_at: "2024-11-01T00:00:00Z",
    updated_at: "2025-03-05T00:00:00Z",
  },
  {
    id: "course-5",
    title: "UI/UX Design Fundamentals",
    slug: "ui-ux-design-fundamentals",
    description:
      "Learn the principles of great design. From wireframing to prototyping, build beautiful and user-friendly interfaces using Figma.",
    short_description: "Design principles, wireframing & Figma prototyping",
    thumbnail_url: "https://images.unsplash.com/photo-1561070791-2526d30994b5?w=600&q=80",
    instructor_id: "inst-2",
    instructor: MOCK_INSTRUCTORS[1],
    category: "Design",
    level: "Beginner",
    price: 499,
    is_free: false,
    duration_hours: 18.5,
    lessons_count: 30,
    enrolled_count: 9100,
    rating: 4.8,
    ratings_count: 1540,
    tags: ["figma", "ui-design", "ux-research", "prototyping"],
    is_published: true,
    created_at: "2024-12-01T00:00:00Z",
    updated_at: "2025-02-15T00:00:00Z",
  },
  {
    id: "course-6",
    title: "Mobile App Development with React Native",
    slug: "mobile-app-development-react-native",
    description:
      "Build cross-platform mobile apps with React Native and Expo. Covers navigation, state management, native APIs, and publishing to app stores.",
    short_description: "Cross-platform mobile apps with React Native & Expo",
    thumbnail_url: "https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?w=600&q=80",
    instructor_id: "inst-3",
    instructor: MOCK_INSTRUCTORS[2],
    category: "Mobile Development",
    level: "Intermediate",
    price: 499,
    is_free: false,
    duration_hours: 24,
    lessons_count: 38,
    enrolled_count: 5480,
    rating: 4.5,
    ratings_count: 720,
    tags: ["react-native", "expo", "mobile", "typescript"],
    is_published: true,
    created_at: "2025-01-10T00:00:00Z",
    updated_at: "2025-03-18T00:00:00Z",
  },
];

// ─── Testimonials (kept from original) ──────────────────────────────

export const TESTIMONIALS = [
  {
    id: "t1",
    name: "Rohit Verma",
    role: "Frontend Developer at Infosys",
    avatar: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=200&q=80",
    quote:
      "Spire completely transformed my career. The structured learning paths and project-based approach helped me land my dream job within 3 months.",
    rating: 5,
  },
  {
    id: "t2",
    name: "Ananya Desai",
    role: "Data Analyst at Flipkart",
    avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200&q=80",
    quote:
      "The data science course was incredibly well-structured. The instructors explain complex concepts in a way that's easy to understand and apply.",
    rating: 5,
  },
  {
    id: "t3",
    name: "Karthik Nair",
    role: "UX Designer, Freelance",
    avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=200&q=80",
    quote:
      "I loved the hands-on projects and the community support. The certificate I earned from Spire helped me win multiple freelance contracts.",
    rating: 4,
  },
];

// ─── Progress ───────────────────────────────────────────────────────

export const MOCK_PROGRESS: Progress[] = [
  {
    id: "prog-1",
    user_id: "user-1",
    lesson_id: "lesson-1",
    course_id: "course-1",
    status: "completed",
    progress_percent: 100,
    last_accessed_at: "2025-03-20T10:00:00Z",
    completed_at: "2025-03-20T10:00:00Z",
  },
  {
    id: "prog-2",
    user_id: "user-1",
    lesson_id: "lesson-2",
    course_id: "course-1",
    status: "in_progress",
    progress_percent: 65,
    last_accessed_at: "2025-03-22T14:30:00Z",
    completed_at: null,
  },
  {
    id: "prog-3",
    user_id: "user-1",
    lesson_id: "lesson-1",
    course_id: "course-3",
    status: "in_progress",
    progress_percent: 40,
    last_accessed_at: "2025-03-21T09:00:00Z",
    completed_at: null,
  },
];

// ─── Badges & Achievements ─────────────────────────────────────────

export const MOCK_BADGES: Badge[] = [
  {
    id: "badge-1",
    name: "First Steps",
    description: "Complete your first lesson",
    icon_url: "/badges/first-steps.svg",
    criteria: "complete_1_lesson",
    level: "Rookie",
  },
  {
    id: "badge-2",
    name: "Course Conqueror",
    description: "Complete an entire course",
    icon_url: "/badges/course-conqueror.svg",
    criteria: "complete_1_course",
    level: "Developer",
  },
  {
    id: "badge-3",
    name: "Code Streak",
    description: "Maintain a 7-day learning streak",
    icon_url: "/badges/code-streak.svg",
    criteria: "7_day_streak",
    level: "Developer",
  },
  {
    id: "badge-4",
    name: "Knowledge Seeker",
    description: "Enroll in 5 different courses",
    icon_url: "/badges/knowledge-seeker.svg",
    criteria: "enroll_5_courses",
    level: "Expert",
  },
  {
    id: "badge-5",
    name: "Spire Master",
    description: "Complete 10 courses with a rating above 80%",
    icon_url: "/badges/spire-master.svg",
    criteria: "complete_10_courses_80_percent",
    level: "Master",
  },
];

export const MOCK_ACHIEVEMENTS: Achievement[] = [
  {
    id: "ach-1",
    user_id: "user-1",
    badge_id: "badge-1",
    badge: MOCK_BADGES[0],
    unlocked_at: "2025-01-15T08:00:00Z",
  },
  {
    id: "ach-2",
    user_id: "user-1",
    badge_id: "badge-3",
    badge: MOCK_BADGES[2],
    unlocked_at: "2025-02-22T18:00:00Z",
  },
];
